### ISSUE TITLE
Fail with noise

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#258]
In `academy2016` if we make the YAML illegal:

```
---
title: CoDe Academy
nav_weight: 10
weight: 10
brand-txt: >
    *Co*{: style='color: black; font-style: normal;'}De
    Aca*de*{: style="color: black; font-style: normal;"}my<!--power-icon-->
subtitle: >
  A modern continuous delivery bootcamp for graduates
caption: >
  Four Continuous Delivery Bootcamps - in Denmark and Norway. Each is 5 intense days. Bring your laptop! FREE to attend for Computer Science students and unemployed IT professionals. Enroll NOW!
color: '#f58532'
is_container: true
date_:      2016-06-13
date_end:   2016-09-02
city:       Throughout Scandinavia
event_header:
  img: ../images/pages/academy2016/event-main.jpg
    ribbon: Enroll today
checkout:
  eventbriteid: 24573031599
css_class: academy
sponsors:
  - github
  - napatech
  - danfoss
  - bkultrasound
---

```

The  sponsor include produces no output.

Make the includes fail with noise: Print error to the screen, ...and the console

**Comment by illus0r** [comment]
One way of falling is to call not existing include.
```
{% if false %}
  {% include not_existing_include.html %}
{% endif %}
```

This code will throw no messages. But if I change false to true, I will make a trouble.

```
{% if true %}
  {% include not_existing_include.html %}
{% endif %}
```

![image](https://cloud.githubusercontent.com/assets/797993/16009659/61a78608-3186-11e6-854e-a771ee6c0917.png)

Not very semantic way, I'll search another one.

**Comment by illus0r** [comment]
Dividing by `0` doesn't work :(
```
{{ "3.0" | divided_by: 0 }}
```
is `Infinity`

**Comment by lakruzz** [comment]
Or build resilience into everything we do:

1. Why does https://github.com/Praqma/code-conf.com/blob/gh-pages/_includes/sponsors.html fail when the yaml becomes unvaild
2. Make sure it doesn't happen silently

The problem you are trying to solve is best solved in Jekyll: https://github.com/jekyll/jekyll/issues/4713

**Comment by illus0r** [comment]
@lakruzz 
Sorry, I didn't get your idea. I've read the Jekyll issue through, but the problem isn't solved by jekyll guys. Wrong YAML is processed with `0` exit code
![image](https://cloud.githubusercontent.com/assets/797993/16077251/5d07caec-3300-11e6-8517-70db6dc3654a.png)

So i see two ways:

:one: Draw the message on screen. We can provide a short text as well to explain where to fix the error.
```
{% if page.city == null %}
  {% include giant_error_message.html text="City not set, fix /_events/code-cph-2016.md" %}
{% endif %}
```

:two: Call not existing include. We can add some more info here.
```
{% if  page.city == null %}
  {% include not_existing_include.html text="City not found, fix /_events/code-cph-2016.md" %}
{% endif %}
```

All page variables are turned to null if YAML contains an error. That'll help in troubleshooting
```
  title: null
  nav_weight: null
  weight: 9999999
  brand: null
  subtitle: null
  caption: null
  color: null
  is_container: null
  date_: null
  date_end: null
  city: null
  event_header: null
  checkout: null
  css_class: null
  sponsors: null
```
`weight: 9999999` defined by `_config.yml`

**Comment by illus0r** [comment]
Added asserts to every include, that needed
added var `page_color` to `_config.yml` and used it to make `color` variable to be not obligatory.
If `color` is not set for some events, they will use `site.page_color` instead. Currently, it's black.
